In [77]:
import numpy as np


In [78]:
A = np.array([[1, np.sqrt(2)],
              [2, 2 * np.sqrt(2)]])
right_part = np.array([1, np.sqrt(2)])
alpha = 2
E = np.eye(2)

Первым способом

In [79]:
offs_matr = A + alpha * E

x_alpha = np.linalg.inv(offs_matr) @ right_part

In [80]:
print(x_alpha)

[0.24264069 0.19238816]


Вторым способом


In [92]:
r = np.array([2, -1])
alpha = 1e-2
zero_matr = np.zeros((2,2))
expanded_matrix = np.array([[alpha * E, A], [A.T, np.ones((2,2))]])
expanded_right = np.array([right_part, np.zeros((2,))])
expanded_right = np.array([1, np.sqrt(2), 0, 0])

expanded_matrix = np.zeros((4, 4))

expanded_matrix[:2, :2] = alpha * E
expanded_matrix[:2, 2:] = A
expanded_matrix[2:, :2] = A.T
expanded_matrix[2:, 2:] = E
print(expanded_matrix)

z = np.linalg.inv(expanded_matrix) @ expanded_right
print(z[2:])

[[0.01       0.         1.         1.41421356]
 [0.         0.01       2.         2.82842712]
 [1.         2.         1.         0.        ]
 [1.41421356 2.82842712 0.         1.        ]]
[0.25539874 0.36118836]


Третий способ

In [110]:
expanded_matrix = np.zeros((4, 4))

alpha = 0.1
expanded_matrix[:2, :2] = alpha * E
expanded_matrix[:2, 2:] = A
expanded_matrix[2:, :2] = A.T
expanded_matrix[2:, 2:] = E


z = np.linalg.inv(expanded_matrix + alpha * np.eye(4)) @ expanded_right
print(z)

[ 1.11458682 -0.69975856  0.25902755  0.36632027]


То же самое, но с округлённым f

In [118]:
right_part = np.array([1, round(np.sqrt(2), 3)])

первым способом

In [128]:
alpha = 1.8
offs_matr = A + alpha * E
x_alpha = np.linalg.inv(offs_matr) @ right_part
print(x_alpha)

[0.25946948 0.19338341]


через расширенную

In [130]:
r = np.array([2, -1])
alpha = 1e-2
zero_matr = np.zeros((2,2))
expanded_matrix = np.array([[alpha * E, A], [A.T, np.ones((2,2))]])
expanded_right = np.array([right_part, np.zeros((2,))])
expanded_right = np.array([1, round(np.sqrt(2), 2), 0, 0])

expanded_matrix = np.zeros((4, 4))

expanded_matrix[:2, :2] = alpha * E
expanded_matrix[:2, 2:] = A
expanded_matrix[2:, :2] = A.T
expanded_matrix[2:, 2:] = E
print(expanded_matrix)

z = np.linalg.inv(expanded_matrix) @ expanded_right
print(z[2:])

[[0.01       0.         1.         1.41421356]
 [0.         0.01       2.         2.82842712]
 [1.         2.         1.         0.        ]
 [1.41421356 2.82842712 0.         1.        ]]
[0.25483656 0.36039332]


Третий способ

In [131]:
expanded_matrix = np.zeros((4, 4))

alpha = 0.1
expanded_matrix[:2, :2] = alpha * E
expanded_matrix[:2, 2:] = A
expanded_matrix[2:, :2] = A.T
expanded_matrix[2:, 2:] = E


z = np.linalg.inv(expanded_matrix + alpha * np.eye(4)) @ expanded_right
print(z)

[ 1.12313938 -0.70372124  0.25845737  0.36551392]
